# Generated by Django 4.2.16 on 2024-10-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
